database:
    type: "sqlite3"
    connection: "test.db"
schemas:
    - "embed://etc/schema/gohan.json"
    - "../tests/test_abstract_schema.yaml"
    - "../tests/test_schema.yaml"
    - "../tests/test_schema_sync.yaml"
    - "../tests/test_two_same_relations_schema.yaml"
address: ":19090"
document_root: "embed"
sync: etcdv3
etcd:
    - "http://127.0.0.1:2379"
keystone:
    use_keystone: true
    fake: true
    auth_url: "http://localhost:19090/v2.0"
    user_name: "admin"
    tenant_name: "admin"
    password: "gohan"
cors: "*"

pprof: ":16123"

logging:
  stderr:
    enabled: false
    level: ERROR
